timeout: 5

/System Commander
        protocol: limine
        path: boot():/boot/systemcommander
        module_path: boot():/boot/deffont.psf
        module_string: deffont
        resolution: 1920x1080x32
